### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MisterOcto** [Andrewthe13th/Inventory_Kamera#330] opened 2022-07-23 13:39 UTC
> **NOTE**
> Please describe on each question as much as you can. This will speeds up our bug fixing process.

## What happed? What is seems to be a bug?

Hello i m french and my level in english is a bit bad. I hope you undertand me. When i scanned with inventory kamera, start works normally but for materials and char developement items half is not detected. The error is the following : 
![image](https://user-images.githubusercontent.com/109859140/180607201-3abdb55e-8b3d-4839-87ee-6bd6c9ec6e8b.png)
It's the same error every time. 
![image](https://user-images.githubusercontent.com/109859140/180607417-d237f58e-607f-4d4c-87a4-1665b55c5a2c.png)
It can't scan the numbers, I don't understand why

## How to reproduce this issue

I ran the scanner normally, I tried with several windowed resolutions, HD, FHD and 2k (I paid attention to the 16:9 ratio) and also with fast, slow and slower. The problem is still there.

## What seems to cause this issue?

The scanning of materials and char developement items.

## Info about your device
- Device Operating System : Windows 10
- Genshin Impact Version : the last
- Inventory Kamera Version : the last (1.2.7)
- Screen resolution(s) affected : HD FHD 2K 16:9

## Checklist before sending issue

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [x] I have checked Issue page and there is **none** that is related to mine.
- [x] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [x] I have filled in "Info about your device" section.
- [x] I have correctly set my character and inventory keys in Inventory Kamera
- [x] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

Additional checklist for Scanning issues
- [x] I tried setting the delay to maximum and still experiencing issues.
- [x] I have attached media and log files that Inventory Kamera generates.

**Comment by Cupcak3** [comment] 2022-07-23 17:50
Duplicate of #96 This issue is known and low priority

**Closed by Cupcak3** 2022-07-23 17:50 UTC
Labels: bug, duplicate
