### ISSUE TITLE
Scan aborted for first time

### ISSUE THREAD

**Issue by wMingQAQ** [Andrewthe13th/Inventory_Kamera#293] opened 2022-05-26 15:52 UTC
Tesseract.TesseractException: Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.

   en Tesseract.TesseractEngine.Initialise(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialValues, Boolean setOnlyNonDebugVariables)

   en Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialOptions, Boolean setOnlyNonDebugVariables)

   en InventoryKamera.Scraper.InitEngines()

   en InventoryKamera.Scraper..cctor()

**Comment by balthanon** [comment] 2022-07-03 18:11
I was getting this same error-- when I downloaded the latest version (which was still 2.6) and copied it over my existing installation, the error went away though.  So I'm assuming this happened due to the auto-update for 2.7 for some reason.  The build I got this on was downloaded sometime in May I believe.

**Comment by Cupcak3** [comment] 2022-07-23 19:53
Duplicate of #126

**Closed by Cupcak3** 2022-07-23 19:53 UTC
Labels: bug
