### ISSUE TITLE
Failed to parse quantity when scanning items and materials

### ISSUE THREAD

**Issue by LiuAnshan** [Andrewthe13th/Inventory_Kamera#225] opened 2022-02-19 05:32 UTC
The only issue I found that seemed to mention this seemed specifically for 1.2.1 build so I'm creating this issue. 

I tried a few times at different window resolutions and seemed to have the least amount of failures at 3200x1800 which is 16x9 aspect ratio. 

I'm not sure where to find the first several lines of the stack trace.  I suspect there isn't one since the scanner did not fail or crash. 

It seems that the majority of the failures contain a either a 1 as the first digit or are single digit 1s.  There was one 2, one 3, one 4 and one 8 as well. 

I'm not sure if there are other screenshots that could be helpful, I just grabbed 4 of them. 
Log:

```Unable to parse mora count


Failed to parse quantity for DvalinsPlume


Failed to parse quantity for MoltenMoment


Failed to parse quantity for VajradaAmethystFragment


Failed to parse quantity for PhilosophiesOfTransience


Failed to parse quantity for CrownOfInsight


Failed to parse quantity for BorealWolfsNostalgia


Failed to parse quantity for ShacklesOfTheDandelionGladiator


Failed to parse quantity for MistVeiledGoldElixir


Failed to parse quantity for LungedStickleback


Failed to parse quantity for GoldenKoi


Failed to parse quantity for RustyKoi


Failed to parse quantity for BrownShirakodai


Failed to parse quantity for PurpleShirakodai


Failed to parse quantity for Pufferfish


```

![PhilosophiesOfTransience_Quantity - Copy](https://user-images.githubusercontent.com/19419600/154787627-b0edb3ec-cbe9-412b-b0e8-5377c15326fd.png)
![ShacklesOfTheDandelionGladiator_Quantity](https://user-images.githubusercontent.com/19419600/154787629-3cd82e6e-c79e-4a00-9545-e06934b2cfea.png)
![mora](https://user-images.githubusercontent.com/19419600/154787630-b968c1dd-18da-4fbc-b385-da522c4397cc.png)
![Pufferfish_Quantity](https://user-images.githubusercontent.com/19419600/154787783-9b69da5b-4f66-40f8-9e6c-cbeb5e6a4a97.png)

**Comment by Cupcak3** [comment] 2022-02-20 20:00
Thanks for the report. Unfortunately the scanner isn't the best when it comes to parsing quantities when they're so close to the stars. Single digit quantities as well as digits like 1, 4, 7 can give it a hard time. That and mora scanning are both in need of optimizations.

There's no stack traces because they weren't crashes and we log those images. We also log them as errors so you can know that something failed to scan correctly when you go to upload the exported data to a site. 

I will keep this issue open so that duplicate issues can be redirected to this one.

**Comment by Blonger** [comment] 2022-02-25 23:14
I got thoose errors while scanning with 1920x1080 px resolution, i tried with 50 ms delay got slightly different errors but basically and mostly the same.

`Failed to parse quantity for ChaosCore


Failed to parse quantity for MistGrassWick


Failed to parse quantity for InspectorsSacrificialKnife


Failed to parse quantity for FossilizedBoneShard


Failed to parse quantity for CrystalPrism


Failed to parse quantity for ConcealedUnguis


Failed to parse quantity for TearsOfTheCalamitousGod


Failed to parse quantity for TheMeaningOfAeons


Failed to parse quantity for CleansingHeart


Failed to parse quantity for PerpetualHeart


Failed to parse quantity for PhilosophiesOfProsperity


Failed to parse quantity for GuideToTransience


Failed to parse quantity for JeweledBranchOfADistantSea


Failed to parse quantity for GoldenBranchOfADistantSea


Failed to parse quantity for MistVeiledMercuryElixir


Failed to parse quantity for MistVeiledPrimoElixir


Failed to parse quantity for DebrisOfDecarabiansCity


Failed to parse quantity for VenomspineFish


Failed to parse quantity for Snowstrider


Failed to parse quantity for RustyKoi


Failed to parse quantity for DivdaRay


`

**Comment by Cupcak3** [comment] 2022-07-23 18:38
Duplicate of #96

**Closed by Cupcak3** 2022-07-23 18:38 UTC
