### ISSUE TITLE
artifact show wrong %  in substats

### ISSUE THREAD

**Issue by iKamus** [Andrewthe13th/Inventory_Kamera#110] opened 2021-12-17 10:21 UTC
it show in the GO all the artifact with wrong substats %
![ARTIFACTs](https://user-images.githubusercontent.com/10860419/146528362-67b24a2e-4b59-453b-87a1-d2c6b0a89379.png)
this is how GO show them
![GOartifact](https://user-images.githubusercontent.com/10860419/146529191-8b08ae84-5bb9-45a0-9115-c5f5945ba6bd.png)

idk how to upload the json file that inventorykamera did so can check out

**Comment by Ancillius** [comment] 2021-12-17 16:02
Can confirm, same here.. artefact substats are not read correctly and some artifacts/weapons are skipped

**Comment by Cupcak3** [comment] 2021-12-17 19:05
Thanks for the report. Clearly it looks like the scanner is not picking up the decimal period. What resolution did you scan in?

**Comment by Ancillius** [comment] 2021-12-18 00:23
I tried to scan all supported resolutions (v1.1 tag/release description) and the default one (the programm states to use) .. no difference.. tried also to tinker with the render resolution ingame... no change.

Workaround was to read the json export, divide all values by 10 and write it back... but surely this is not a solution for everybody.

**Comment by Cupcak3** [comment] 2021-12-18 00:33
You are right that's not an ideal workaround on the user end. I've been unable to reproduce the issue while testing, however a fix is on the dev branch.

**Comment by bigfatjoe87** [comment] 2021-12-18 10:23
same problem here
![grafik](https://user-images.githubusercontent.com/96334839/146637640-45b91610-4bcf-4c70-8846-1ae0122810cf.png)
scan with v1.1 1600x900 (with 1280x720 dosent work)

**Comment by iKamus** [comment] 2021-12-20 01:03
> You are right that's not an ideal workaround on the user end. I've been unable to reproduce the issue while testing, however a fix is on the dev branch.

thx for fixing it, how we download the one from dev branch? or we need wait ?

**Comment by anzmore** [comment] 2021-12-21 20:48
same problem here every stat with % have the digit in the wrong position tryed a many different resolution and graphics settings but the problem stay there

**Comment by SplaTTerChef** [comment] 2021-12-22 00:18
I fixed it with using an older version and replace the old artifact code in the new version. Just copy & paste. It worked :D

**Comment by bagusnl** [comment] 2021-12-23 00:54
Issue still present on devel branch PR #128

**Comment by vhtNov17** [comment] 2021-12-28 04:47
here's my quick fix 
copy and paste these in find & replace field on a text editor that supports RE: 
(find input)
_","value":(\d)(\d)?(\d)\.0
(replace input)
_","value":$1$2.$3

**Comment by lamedroid** [comment] 2021-12-28 15:43
> here's my quick fix
> 
> 1. open the json file with a text editor that supports RegEx
> 2. copy and paste these in find & replace field:
>    (find input)
>    _","value":(\d)(\d)?(\d).0
>    (replace input)
>    _","value":$1$2.$3
> 
> i know some people do not understand my temp solution but those who do should give a try 👍

Thx! I use Editpad pro and tried to work it out, but can't. Could you elaborate a bit?

**Comment by iKamus** [comment] 2021-12-29 00:06
well im being using the other scanner for artifact Amenoma_EN and using this one for characters that work ok

**Comment by vhtNov17** [comment] 2021-12-29 03:36
> > here's my quick fix
> > 
> > 1. open the json file with a text editor that supports RegEx
> > 2. copy and paste these in find & replace field:
> >    (find input)
> >    _","value":(\d)(\d)?(\d).0
> >    (replace input)
> >    _","value":$1$2.$3
> > 
> > i know some people do not understand my temp solution but those who do should give a try 👍
> 
> Thx! I use Editpad pro and tried to work it out, but can't. Could you elaborate a bit?

i recommend using Sublime Text
here are the specific steps:
1. open the .json file with ST
![image](https://user-images.githubusercontent.com/81290839/147624806-2ef84431-8626-47eb-babd-38cc9a4f2c43.png)
2. ctrl + h
![image](https://user-images.githubusercontent.com/81290839/147624850-d399ee8d-ad5f-460e-871e-d4202a32aafb.png)
3. hit this
![image](https://user-images.githubusercontent.com/81290839/147624903-6ca64e27-114b-4534-8d10-168c7a71e1b5.png)
4. copy paste these in find & replace fields:
find:
_","value":(\d)(\d)?(\d).0
replace:
_","value":$1$2.$3
![image](https://user-images.githubusercontent.com/81290839/147624984-385d333c-f10f-4543-86c6-867765e6fd95.png)
5. click Replace All. Done

**Comment by vhtNov17** [comment] 2021-12-29 03:47
> well im being using the other scanner for artifact Amenoma_EN and using this one for characters that work ok
Amenoma works well but we have to equip every weapons and artifacts by hand on GO which is painful if we got many characters.
plus, Amenoma doesnt scan weapons and characters (most importantly their talents' lv) only artifacts

**Comment by vhtNov17** [comment] 2021-12-29 03:47
> well im being using the other scanner for artifact Amenoma_EN and using this one for characters that work ok

Amenoma works well but we have to equip every weapons and artifacts by hand on GO which is painful if we got many characters.
plus, Amenoma doesnt scan weapons and characters (most importantly their talents' lv) only artifacts

**Comment by iKamus** [comment] 2021-12-29 05:32
> > well im being using the other scanner for artifact Amenoma_EN and using this one for characters that work ok
> 
> Amenoma works well but we have to equip every weapons and artifacts by hand on GO which is painful if we got many characters. plus, Amenoma doesnt scan weapons and characters (most importantly their talents' lv) only artifacts

yes but IK working perfect for me for characters and weapons and only need artifact ofc is much better if all at once so is just wait until dev release a new build with artifact working

**Comment by vhtNov17** [comment] 2021-12-29 05:40
> yes but IK working perfect for me for characters and weapons and only need artifact ofc is much better if all at once so is just wait until dev release a new build with artifact working

you could try my method since it requires zero coding knowledge just copy and paste and works surprisingly fast 🐎

**Comment by lamedroid** [comment] 2022-01-03 11:48
> > > here's my quick fix
> > > \
Thanks you so much for the "tutorial"!!!!

**Comment by Cupcak3** [comment] 2022-01-11 22:31
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.

**Comment by iKamus** [comment] 2022-01-12 01:44
> Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.

it working perfect now ty for update

**Closed** 2022-01-12 02:06 UTC

**Comment by lamedroid** [comment] 2022-01-13 10:45
> Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.

Same for me! Thanks!
