### ISSUE TITLE
Weapon scanner does not read 110 properly

### ISSUE THREAD

**Issue by jianwen-android** [Andrewthe13th/Inventory_Kamera#83] opened 2021-12-04 13:11 UTC
![image](https://user-images.githubusercontent.com/65391811/144710524-ffc762fa-9d44-4693-bd42-6c17bb1a9c6b.png)

As you can see it appears that the scanner saw that I had 10 weapons, when in reality

![image](https://user-images.githubusercontent.com/65391811/144710554-5dd16b8b-11ee-4df6-9787-c2b224f782a0.png)

I have a 110 weapons in the inventory

After I used 10 weapons to upgrade and bring the number down to 100, the scanner was able to work fine again

![image](https://user-images.githubusercontent.com/65391811/144710709-fbc555c7-9ed3-468b-8f24-9037ab169918.png)
![image](https://user-images.githubusercontent.com/65391811/144710710-3fcb2ab6-21dd-48c1-a42c-36dd3bd71328.png)

**Comment by Andrewthe13th** [comment] 2021-12-04 13:36
Thanks for taking an image. I will test this number in the future as a test case.

**Comment by lhunath** [comment] 2021-12-09 02:26
Same here for 111. Reads as 11.
![image](https://user-images.githubusercontent.com/36948/145322875-98c1323e-980b-435e-8653-9b806d33e0ed.png)
![image](https://user-images.githubusercontent.com/36948/145323140-20c55aa5-6d5e-4054-bc07-1f9786334895.png)

**Comment by MillingtonAllen** [comment] 2021-12-10 02:56
I'm having a similar issue with 900 artifacts reading as only 90.

**Comment by jianwen-android** [comment] 2021-12-10 16:04
![image](https://user-images.githubusercontent.com/65391811/145604191-efc6d2ab-0186-459c-887b-9fca5a51dad9.png)

It appears that anything with double 1 will also cause it to misread

**Comment by Cupcak3** [comment] 2022-01-11 22:15
Duplicate of #48

**Comment by sagelga** [comment] 2022-05-30 10:24
This Issue should be closed since this one is marked duplicate.
@Cupcak3

**Closed** 2022-06-06 10:09 UTC
Labels: duplicate
