### ISSUE TITLE
[Bug] Scanner Crashes with less than 1 page of Inventory Items

### ISSUE THREAD

**Issue by TheNameIs-M** [Andrewthe13th/Inventory_Kamera#487] opened 2023-12-13 15:53 UTC
### Current Behavior

I am trying to scan my boyfriend's account with the inventory kamera. He's just starting out but it's good to keep track of materials so he can level up the characters he _does_ have. The application does not work, however and refuses to scan anything on the weapons page at the moment. Which is weird because a few days ago when I did try to scan it, it worked somewhat, but it skipped the entire first row of weapons he has. I don't have a video of the row skipping, but I have a video of it just not working at all for weapons, but artifact scan seems fine (and I assume everything else after works fine considering).

I am not sure if it's being weird because I've also used it to scan my own account before (haven't tried it recently though) and it's expecting my account somehow? I have Wanderer and he doesn't, he just finished the Liyue Archon Quest so he hasn't even gotten to name Wanderer yet. I even tried putting "Wanderer" in the slot for Wanderer's Name, in case it was bugging out because of that, but nothing worked.

https://github.com/Andrewthe13th/Inventory_Kamera/assets/143708801/ab93857b-95fe-464e-be23-dae959c92a57

### Expected Behavior

The scanner to not skip rows or items

### Reproducing a Behavior

I'm not sure how to reproduce it since I'm not sure if it's specific to me, but generally, I literally just open up IK, have Genshin open at 1600x900 windowed mode, and scan like usual. The specs are as follows:

![image](https://github.com/Andrewthe13th/Inventory_Kamera/assets/143708801/039afbe9-9ffa-4e22-a4d3-5296c4b1f126)

### Device OS

Windows 11

### Genshin Impact Version

4.2

### Inventory Kamera Version

1.3.11

### Screen resolution, screen mode, and UI scale

1600x900, tried 1280x720

### Additional notes and remarks

I don't mind just manually entering his inventory data into the website I'm using, especially since he doesn't even have much in his new account anyway, it just doesn't make sense for IK to be doing this regardless.

Update:
I just tried it with my account, and it works perfectly fine. Not sure what's happening, in any case, if the issue is my boyfriend's account.
https://github.com/Andrewthe13th/Inventory_Kamera/assets/143708801/7fec8deb-e588-4af8-9e24-1166965c3f36

### Evidence

[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/13662570/InventoryKamera.debug.log)
Regarding "C:\Users\veloz..." I have no idea where it's getting veloz from, since the only user is me and it's set to my name, which isn't veloz.

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment] 2024-02-03 21:33
I've changed the title to be more reflective of the root cause. I will look into a fix

**Comment by Cupcak3** [comment] 2024-02-03 22:30
Actually, I am closing this in favor of #316

**Closed by Cupcak3** 2024-02-03 22:30 UTC
Labels: bug
