### ISSUE TITLE
Struggling with materials

### ISSUE THREAD

**Issue by nikidash** [Andrewthe13th/Inventory_Kamera#243] opened 2022-03-15 00:52 UTC
Latest release, attempting to scan in windowed 1600x900. It's really struggling with materials for some reason. No filters of any sort going on, and it has no problem scanning weapons, artifacts and characters.

```
Unable to parse mora count


Failed to parse quantity for ChaosCore


Failed to parse quantity for InspectorsSacrificialKnife


Failed to parse quantity for SpectralNucleus


Failed to parse quantity for DvalinsPlume


Failed to parse quantity for TailOfBoreas


Failed to parse quantity for RingOfBoreas


Failed to parse quantity for SpiritLocketOfBoreas


Failed to parse quantity for TuskOfMonocerosCaeli


Failed to parse quantity for ShardOfAFoulLegacy


Failed to parse quantity for ShadowOfTheWarrior


Failed to parse quantity for DragonLordsCrown


Failed to parse quantity for GildedScale


Failed to parse quantity for HellfireButterfly


Failed to parse quantity for VayudaTurquoiseGemstone


Failed to parse quantity for VayudaTurquoiseFragment


Failed to parse quantity for PrithivaTopazGemstone


Failed to parse quantity for PhilosophiesOfFreedom


Failed to parse quantity for PhilosophiesOfResistance


Failed to parse quantity for GuideToBallad


Failed to parse quantity for GuideToProsperity


Failed to parse quantity for ScatteredPieceOfDecarabiansDream


Failed to parse quantity for BorealWolfsBrokenFang


Failed to parse quantity for DivineBodyFromGuyun


Failed to parse quantity for NorthlanderPolearmBillet


Failed to parse quantity for GlazeMedaka


Failed to parse quantity for Dawncatcher


Failed to parse quantity for Crystalfish


Failed to parse quantity for AkaiMaou


Failed to parse quantity for BrownShirakodai


Failed to parse quantity for TeaColoredShirakodai



```

**Comment by Cupcak3** [comment] 2022-05-16 03:16
Hi there, I know it's been a while since this issue was opened but (V1.2.5)[https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5] has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!

**Comment by nikidash** [comment] 2022-05-18 22:45
Hi! I did a quick test with materials and char dev items. At 1600x900 much improved, though still struggles with the item count of several things. Did one run at 1920x1080, went flawless
Log included

[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8721314/InventoryKamera.log)
.

**Comment by Cupcak3** [comment] 2022-07-23 18:49
Duplicate of #96

**Closed by Cupcak3** 2022-07-23 18:49 UTC
