### ISSUE TITLE
Issues observed with automatic navigation and character recognition

### ISSUE THREAD

**Issue by paradoxrevolver** [Andrewthe13th/Inventory_Kamera#226] opened 2022-02-19 08:48 UTC
i was planning on testing a couple different resolutions and scanner delays and using a diff checker to compare the contents of the error logs and GOOD files, so i could figure out what would reduce the number of reading errors as much as possible. but it also seems like it might help if i post what i found here!

i tested the following four configurations, each of them exactly once:

- 1280x720 with a delay of 0ms
- 1600x900 with a delay of 0ms
- 1600x900 with a delay of 50ms
- 1600x900 with a delay of 100ms

i've attached folders for each of these configurations, which contain the logging/ folder that was generated, the error log, and the resulting GOOD file.

[1280x720_0ms.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/8101650/1280x720_0ms.zip)
[1600x900_0ms.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/8101652/1600x900_0ms.zip)
[1600x900_50ms.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/8101656/1600x900_50ms.zip)
[1600x900_100ms.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/8101658/1600x900_100ms.zip)

here are some observations:

- the first row of the Weapons tab was consistently ignored. in all test cases, the scanner started from the first weapon on the second row and proceeded as normal. this was not the case before, with IK V1.2.
- from what i can tell, artifacts were recorded correctly every time. sometimes they were out of order in the JSON array, but their ID numbers always matched their details, and for all the recorded artifacts i compared with my actual artifacts in-game, everything was recorded correctly.
- the numbers 1, 2, 4, 8, 9, 10, and 11 are misread frequently by the OCR in the Materials menu. the same materials had a tendency to get misread repeatedly, and i think this is the OCR having trouble with these digits.
- for a small number of weapons, weapon ascension was misread at 1280x720, but was read correctly by all of the 1600x900 tests.
- mora was misread as zero by the two 0ms tests, but was read correctly by the 50ms and 100ms tests.
- the higher resolution generally resulted in fewer errors, but not by much. i used the 1600x900_0ms as the test i compare to the others because it seemed to be the most correct one.

out of my own curiosity, i wrote the correct values for a few of my materials and then cross referenced that with the two 0ms tests. the red lines in the below image indicate which materials were misread by both tests:

![Code_2022-02-19_00-26-45](https://user-images.githubusercontent.com/18134512/154793532-4029c837-9817-49dd-800f-c14f032fcc64.png)

i don't have a huge wealth of materials since i haven't played the game for very long, which probably made my total scan times shorter than the average player. i also recognize that i would have to do a lot more tests to say anything was very consistent, but hopefully this helps in identifying problem areas!

i can provide any other information you might need if it's not already in the files i've uploaded. i also want to say thank you, optimizing genshin has been a great deal of fun for me lately and i'm super grateful that projects like these are being actively worked on!

**Comment by Cupcak3** [comment] 2022-02-19 19:11
- I'll take a look at the zips you provided to figure out what's going on with the first row of weapons being skipped
- Single digits and low quantities are low accuracy right now. We're working on getting that better 
- Mora scanning will also probably need to be readjusted for the new UI as well

Your screenshots will help in testing when I have time to take a better look at fixing things.

**Comment by Cupcak3** [comment] 2022-07-23 18:39
Duplicate of #96

**Closed by Cupcak3** 2022-07-23 18:39 UTC
