### ISSUE TITLE
Getting this error message after trying to scan again. downloaded the x64 and 86 so Idk

### ISSUE THREAD

**Issue by Kyrims** [Andrewthe13th/Inventory_Kamera#250] opened 2022-03-28 19:57 UTC
System.TypeInitializationException: The type initializer for 'InventoryKamera.Scraper' threw an exception. ---> Tesseract.TesseractException: Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.

   at Tesseract.TesseractEngine.Initialise(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialValues, Boolean setOnlyNonDebugVariables)

   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialOptions, Boolean setOnlyNonDebugVariables)

   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode)

   at InventoryKamera.Scraper..cctor()

   --- End of inner exception stack trace ---

   at InventoryKamera.Scraper.RestartEngines()

   at InventoryKamera.InventoryKamera.GatherData()

   at InventoryKamera.MainForm.<StartButton_Clicked>b__12_0()

**Comment by Cupcak3** [comment] 2022-07-23 18:52
Duplicate of #126

**Closed by Cupcak3** 2022-07-23 18:52 UTC
