### ISSUE TITLE
3.3 patch the scanner stopped scanning after first artifact.

### ISSUE THREAD

**Issue by nammerduong** [Andrewthe13th/Inventory_Kamera#404] opened 2022-12-07 05:35 UTC
### Current Behavior

I don't know if it's the new patch but this app wont scan more than 1 artifact anymore. I am using the new 1.3.3 version but tried to scan on older versions too and still failed. I should mention that when the scan finishes, for some reason a new folder named "Inventory_KameraV1.3.0" gets made on my desktop and that's where the export folder goes into. I also tried to change the game's resolution but the scanner still wont function anymore.

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

be in paimon escape menu and press scan genshin. It wont scan more than 1 artifact.

### Device OS

Windows 10

### Genshin Impact Version

3.3

### Inventory Kamera Version

1.3.3

### Screen resolution, screen mode, and UI scale

1600*900

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment] 2022-12-07 06:11
It would appear that HoYo broke something with their inventory in the new update that impacts scanning. The item cards no longer retain the correct scrolled positions when changing resolutions. In previous Genshin versions this did not happen and the scroll was always set automatically to the top. Since the scanner assumed this to always be the case, it will break if the item description is not scrolled to the top.

### **_Ensuring the item region is scrolled to the top should be enough of a workaround for now._**

I may get out an update to safeguard against tomorrow or something, but I consider this a bug with the game and should be addressed there.

Here's a visualization of what I mean:
![image](https://user-images.githubusercontent.com/8845977/206101008-bcea43e5-8e9d-45cf-bda9-19c516c95684.png)
![image](https://user-images.githubusercontent.com/8845977/206101027-1add4a52-b003-491a-a0eb-456fa1ad3fc3.png)
These are full monitor captures of  1600x900 -> 1920x1080 resolution changes. The only actions I take are to exit the inventory, change the resolution, and enter the inventory again. As you can see the item card is not scrolled to the top like it is in the first image.

**Comment by teddster2002** [comment] 2023-02-23 14:28
ive ran into the same problem but i keep getting the 'Unable to locate artifact count.' error

**Comment by Cupcak3** [comment] 2023-08-12 03:00
A fix was implemented for this issue a while back. Hoyo has also fixed the root cause. The fix is no longer necessary but scanning still appears to work so I am closing this issue as fixed.

**Closed by Cupcak3** 2023-08-12 03:00 UTC
Labels: bug
