### ISSUE TITLE
Failed to parse quantity for some materials

### ISSUE THREAD

**Issue by nitzjr** [Andrewthe13th/Inventory_Kamera#245] opened 2022-03-17 09:58 UTC
1600x900

------------------------------------------------------

Failed to parse quantity for SlimeConcentrate

Failed to parse quantity for WeatheredArrowhead

Failed to parse quantity for EnergyNectar

Failed to parse quantity for SturdyBoneShard

Failed to parse quantity for SpectralNucleus

Failed to parse quantity for DvalinsPlume

Failed to parse quantity for DvalinsClaw

Failed to parse quantity for RingOfBoreas

Failed to parse quantity for TuskOfMonocerosCaeli

Failed to parse quantity for DragonLordsCrown

Failed to parse quantity for GildedScale

Failed to parse quantity for MoltenMoment

Failed to parse quantity for BrilliantDiamondGemstone

Failed to parse quantity for VarunadaLazuriteGemstone

Failed to parse quantity for VajradaAmethystGemstone

Failed to parse quantity for VajradaAmethystChunk

Failed to parse quantity for VayudaTurquoiseGemstone

Failed to parse quantity for VayudaTurquoiseChunk

Failed to parse quantity for VayudaTurquoiseFragment

Failed to parse quantity for ShivadaJadeGemstone

Failed to parse quantity for GuideToResistance

Failed to parse quantity for PhilosophiesOfDiligence

Failed to parse quantity for GuideToDiligence

Failed to parse quantity for PhilosophiesOfGold

Failed to parse quantity for PhilosophiesOfElegance

Failed to parse quantity for GuideToElegance

Failed to parse quantity for ScatteredPieceOfDecarabiansDream

Failed to parse quantity for FragmentOfDecarabiansEpic

Failed to parse quantity for DebrisOfDecarabiansCity

Failed to parse quantity for BorealWolfsBrokenFang

Failed to parse quantity for ChainsOfTheDandelionGladiator

Failed to parse quantity for MaskOfTheTigersBite

Failed to parse quantity for NarukamisJoy

Failed to parse quantity for JeweledBranchOfADistantSea

Failed to parse quantity for NorthlanderBowBillet

**Comment by Cupcak3** [comment] 2022-05-16 03:16
Hi there, I know it's been a while since this issue was opened but [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5) has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!

**Comment by Cupcak3** [comment] 2022-07-23 18:49
Duplicate of #96

**Closed by Cupcak3** 2022-07-23 18:49 UTC
