### ISSUE TITLE
[BUG] ATK Sands results into invalid in Genshin Optimizier

### ISSUE THREAD

**Issue by jamespmnd** [Andrewthe13th/Inventory_Kamera#290] opened 2022-05-23 15:36 UTC
ATK % Sands is read as invalid in Genshin Optimizer. Account was scanned without issues from the log as well.
Upon upload in Genshin optimizer, not a single ATK % artifact showed up. The rest of the artifacts were fine.

## Info about your device
- Device Operating System : Windows 11
- Genshin Impact Version : 2.6
- Inventory Kamera Version : 1.2.5 (latest as of 5/23/22)
- Screen resolution(s) affected : 1600 x 900 and 1920x1200

## Additional Notes / Remarks
Add any other context about the problem and log files/report here.<br>
If you managed to find any related or similar issue, please paste a link here.

## Checklist before sending issue
Here's everything you should try before sending this issue. Make sure that you have completed it accordingly.

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [ X] I have checked Issue page and there is **none** that is related to mine.
- [X ] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [X ] I have filled in "Info about your device" section.
- [ X] I have correctly set my character and inventory keys in Inventory Kamera
- [ X] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

Additional checklist for Scanning issues
> Instruction: If your issue does not relate to scanning issue, feel free to delete any unrelated checklist.
- [ X] I tried setting the delay to maximum and still experiencing issues.

**Comment by Cupcak3** [comment] 2022-05-24 00:56
Please check to see if those goblets missing goblets are in the export file at all or upload it here. If those artifacts are not in the file at all, then that's one problem. If they are in the file, please double check that the values reflect the actual in-game artifact. There's no way to know what the problem is without an upload.

**Comment by AneJlbcuH4uk** [comment] 2022-05-25 17:17
Have same issue today. The problem is that scanner wrote wrong mainstat def not def_, atk not atk_ , hp not hp_ into json file. Changing this stats manualy fixed the issue at least for me.

**Comment by jamespmnd** [comment] 2022-05-26 12:27
> Have same issue today. The problem is that scanner wrote wrong mainstat for sands circlets and goblets (def not def_, atk not atk_ , hp not hp_) into json file. Changing this stats manualy fixed the issue at least for me.

Sorry a bit of a newbie here, how did you change it manually? Which program did you use? 
In connection to this, seeing as there might be hundreds of atk entries in the file, how did you sort out which ones to replace?

**Comment by Cupcak3** [comment] 2022-09-05 22:21
This should be fixed in recent versions.

**Closed by Cupcak3** 2022-09-05 22:21 UTC
Labels: bug
