### ISSUE TITLE
Scanner fails to scan certain characters + fails to scan polearms?

### ISSUE THREAD

**Issue by RavenMC07** [Andrewthe13th/Inventory_Kamera#228] opened 2022-02-20 04:30 UTC
After reporting the previous issue of the IK scanning all characters as c6, I figured well, I'll just edit my character constellation on the Optimizer website, no big deal....
Then I noticed I didn't see all my characters... and that 2 of the characters that I could see (Rosaria and Raiden) were definitely not meant to be holding Beginner's Protectors. They are holding Jade Spear and The Catch respectively (and have been for a long time now).. don't know how that happened. Xiangling was still scanned correctly, holding Dragon's Bane. I watched it scan all my characters, weapons and artifacts and yet I'm still missing:
Mona C2 LVL80, Kaeya C1 LVL80, Fischl C2 LVL80,  Aloy LVL55, Beidou C3 LVL50, Barbara C4 LVL50, Xiao LVL40, Shenhe LVL40/50, Chongyun LVL40, Lisa C2 LVL40, Xinyan C2 LVL40, Amber LVL40
![unknown](https://user-images.githubusercontent.com/76050519/154828448-5c0d3f94-f637-4896-b8d9-920c93f84e27.png)

**Comment by RavenMC07** [comment] 2022-02-20 04:32
If you can't see the top row of the image, it's (from left to right) Bennett, Eula, Diona, Raiden, Razor.

**Comment by Cupcak3** [comment] 2022-02-20 19:44
Thanks for the report. This might have happened if the scanner stopped early when scanning through your party. Right now it works on a simple pass-fail system and once it fails to scan a character it stops scanning. I've noticed bright backgrounds for geo and cryo characters can cause this to happen. We'll work on implementing a more complete method for character scanning.

**Comment by kazerniel** [comment] 2022-03-03 17:21
I don't have many characters, but a few days ago I got the first major scanning bug where my Xingqiu was scanned as Xinyan. He scanned all right before. (the delay is set as 100ms)

**Comment by Cupcak3** [comment] 2022-07-23 18:41
Probably a duplicate of #227

**Closed by Cupcak3** 2022-07-23 18:41 UTC
