### ISSUE TITLE
Cannot find Genshin Impact process.    

### ISSUE THREAD

**Issue by mzname** [Andrewthe13th/Inventory_Kamera#188] opened 2022-01-28 13:43 UTC
Cannot find Genshin Impact process

未将对象引用设置到对象的实例。

   在 InventoryKamera.Navigation.InitializeProcess(String processName) 位置 B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Navigation.cs:行号 339

   在 InventoryKamera.Navigation.Initialize(String processName) 位置 B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Navigation.cs:行号 35

   在 InventoryKamera.Form1.<StartButton_Clicked>b__12_0() 位置 B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:行号 161

In game, I have already change language into English.
It seems that Kamera cannot recognize chinese genshin impact process [YuanShen.exe] ?

![image](https://user-images.githubusercontent.com/14961236/151556870-0d337138-81ec-4893-ab20-068eca623aa3.png)

**Comment by ShiinaRio** [comment] 2022-01-28 15:22
你的问题写得比我详细多了 👍

**Comment by Cupcak3** [comment] 2022-01-28 20:01
Duplicate of #187

I have a fix written for this and hope to release it soon.

**Comment by Cupcak3** [comment] 2022-02-06 20:30
Support for the Chinese client has been added in the [v1.2.1-prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prerelease).

**Closed by Cupcak3** 2022-02-06 20:30 UTC
Labels: duplicate
