### ISSUE TITLE
[BUG] Could not check for updates

### ISSUE THREAD

**Issue by Ravenora** [Andrewthe13th/Inventory_Kamera#306] opened 2022-06-06 10:55 UTC
> **NOTE**
> Please describe on each question as much as you can. This will speeds up our bug fixing process.

## What happed? What is seems to be a bug?

 Upon opening the app, I'm met with a text box titled "Game Version Update" saying "Could not check for updates. Consider trying again in an hour or so.", 
![image](https://user-images.githubusercontent.com/76664407/172146889-660d7a0d-779a-4c1b-883c-462217602484.png)
Clicking "Update Lookup Tables" results in another text box named "Update failed" saying "Unable to update lookup data. Please check log for more details."
![image](https://user-images.githubusercontent.com/76664407/172147084-64c00de7-8632-4a50-bfe1-15570cb40929.png)

## How to reproduce this issue

 Opening the app and clicking update lookup tables in options menu.

## What seems to cause this issue?

 The log file suggests that it could not determine remote version from commits, I have no idea what that means. 

## Expected behavior
 I expect it to successfully update and configure itself upon startup and clicking the update lookup tables option

## Info about your device
- Device Operating System : Windows 10 Home
- Genshin Impact Version : 2.7
- Inventory Kamera Version : 1.2.6
- Screen resolution(s) affected : 1920 x 1080

## Additional Notes / Remarks

[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8843859/InventoryKamera.log)
[InventoryKamera.debug.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/8843860/InventoryKamera.debug.log)

## Checklist before sending issue

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [x] I have checked Issue page and there is **none** that is related to mine.
- [x] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [x] I have filled in "Info about your device" section.
- [x] I have correctly set my character and inventory keys in Inventory Kamera
- [x] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

**Comment by vivienicepig** [comment] 2022-06-11 08:33
This is because webclient not download file as utf8 encoding.
Edit DatabaseManager.cs function LoadJsonFromURLAsync to below solve the problem...

`		private string LoadJsonFromURLAsync(string url)
		{
			string json = "";
			using (WebClient client = new WebClient())
			{
				client.Encoding = Encoding.UTF8;
				json = client.DownloadString(url);
			}
			return json;
		}`

**Comment by daaurpoj** [comment] 2022-06-12 21:48
> This is because webclient not download file as utf8 encoding. Edit DatabaseManager.cs function LoadJsonFromURLAsync to below solve the problem...
> 
> ` private string LoadJsonFromURLAsync(string url) { string json = ""; using (WebClient client = new WebClient()) { client.Encoding = Encoding.UTF8; json = client.DownloadString(url); } return json; }`

Where is this file? I cannot locate it in the most recent release

**Comment by vivienicepig** [comment] 2022-06-12 23:49
File: InventoryKamera\data\DatabaseManager.cs
Search function name: LoadJsonFromURLAsync

**Comment by vivienicepig** [comment] 2022-06-12 23:49
> > This is because webclient not download file as utf8 encoding. Edit DatabaseManager.cs function LoadJsonFromURLAsync to below solve the problem...
> > ` private string LoadJsonFromURLAsync(string url) { string json = ""; using (WebClient client = new WebClient()) { client.Encoding = Encoding.UTF8; json = client.DownloadString(url); } return json; }`
> 
> Where is this file? I cannot locate it in the most recent release

File: InventoryKamera\data\DatabaseManager.cs
Search function name: LoadJsonFromURLAsync

**Comment by daaurpoj** [comment] 2022-06-13 02:55
> > > This is because webclient not download file as utf8 encoding. Edit DatabaseManager.cs function LoadJsonFromURLAsync to below solve the problem...
> > > ` private string LoadJsonFromURLAsync(string url) { string json = ""; using (WebClient client = new WebClient()) { client.Encoding = Encoding.UTF8; json = client.DownloadString(url); } return json; }`
> > 
> > 
> > Where is this file? I cannot locate it in the most recent release
> 
> It's in source code. No in releases. File: InventoryKamera\data\DatabaseManager.cs Search function name: LoadJsonFromURLAsync
> 
> You have to use visual studio to recompile...

Sorry, I'm pretty new to this. Not sure this is the right place to ask, but when I try and clone your repo over to Visual Studio to recompile, I get this error:

"C:\Users\Cody\Source\Repos\Inventory_Kamera\InventoryKameraTests\InventoryKameraTests.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\Cody\Source\Repos\Inventory_Kamera\InventoryKameraTests\InventoryKameraTests.csproj'.  C:\Users\Cody\Source\Repos\Inventory_Kamera\InventoryKameraTests\InventoryKameraTests.csproj"

Do you have any idea why, or a place this question is more appropriate for?

**Comment by daaurpoj** [comment] 2022-06-13 03:10
> > > This is because webclient not download file as utf8 encoding. Edit DatabaseManager.cs function LoadJsonFromURLAsync to below solve the problem...
> > > ` private string LoadJsonFromURLAsync(string url) { string json = ""; using (WebClient client = new WebClient()) { client.Encoding = Encoding.UTF8; json = client.DownloadString(url); } return json; }`
> > 
> > 
> > Where is this file? I cannot locate it in the most recent release
> 
> It's in source code. No in releases. File: InventoryKamera\data\DatabaseManager.cs Search function name: LoadJsonFromURLAsync
> 
> You have to use visual studio to recompile...



> > > This is because webclient not download file as utf8 encoding. Edit DatabaseManager.cs function LoadJsonFromURLAsync to below solve the problem...
> > > ` private string LoadJsonFromURLAsync(string url) { string json = ""; using (WebClient client = new WebClient()) { client.Encoding = Encoding.UTF8; json = client.DownloadString(url); } return json; }`
> > 
> > 
> > Where is this file? I cannot locate it in the most recent release
> 
> It's in source code. No in releases. File: InventoryKamera\data\DatabaseManager.cs Search function name: LoadJsonFromURLAsync
> 
> You have to use visual studio to recompile...

I got two errors when trying to recompile:

![image](https://user-images.githubusercontent.com/6137571/173272712-efff2e73-453d-4545-942f-2eff71ee6533.png)

Is there anything I can do for them?

**Comment by Maelstrom-Portal** [comment] 2022-06-14 11:36
https://github.com/Andrewthe13th/Inventory_Kamera/issues/298#issuecomment-1146819822

A general fix for Windows regarding UTF-8 issue

**Comment by Ravenora** [comment] 2022-06-16 11:06
> [#298 (comment)](https://github.com/Andrewthe13th/Inventory_Kamera/issues/298#issuecomment-1146819822)
> 
> A general fix for non-English Windows users regarding similar UTF-8 issue.

I've already seen this thread and followed all the steps written, it simply did not work and my issue gives a different error.

**Comment by split-n** [comment] 2022-07-03 03:08
@Maelstrom-Portal  Enabling  "Beta: Use Unicode UTF-8 for worldwide language support" isn't good way to solve the problem. It breaks some application that depends on local charset. Charset should be specified by application.

**Comment by Cupcak3** [comment] 2022-07-09 21:34
Hi there. Sorry for the very late replies to this. I am releasing a build soon that I hope fixes this problem. I have not been able to reproduce this on my own machine so I am hoping the code suggestions are correct and fix the problem.

**Comment by Cupcak3** [comment] 2022-07-23 20:06
V1.2.7 should fix the auto updater. Please let me know if it still persists

**Comment by Maelstrom-Portal** [comment] 2022-07-24 05:23
Fixed on my end, thanks.

**Comment by Cupcak3** [comment] 2022-08-01 03:59
As there has been no further update on this I am going to close this issue. Please reopen the issue to continue any discussion

**Closed by Cupcak3** 2022-08-01 03:59 UTC
Labels: bug
