### ISSUE TITLE
Scanner crashing every time

### ISSUE THREAD

**Issue by LightningDantes** [Andrewthe13th/Inventory_Kamera#99] opened 2021-12-13 13:20 UTC
Started having this issue since 0.9. Every time i try to scan program keep crashing.
Followed all steps/instructions and also checked other crash threads nothing seems to work.
I open game set everything according to instructions and click start scanning as soon as i click scaner sets genshing as main window then it updates itself in navigation section and immideatly crashes. Crash happens right after it updates to state shown in picture.
![Screenshot](https://user-images.githubusercontent.com/32832320/145819698-874192c8-649f-4b3c-afe7-178dde1fd313.jpg)
s

**Comment by Leanny** [comment] 2021-12-15 09:19
I have this issue as well. The exception I get is the following:
```
  System.IndexOutOfRangeException
   at InventoryKamera.GOOD..ctor(InventoryKamera.GenshinData)
   at InventoryKamera.Form1.<button1_Click>b__17_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Andrewthe13th** [comment] 2021-12-15 17:18
Thanks for the report @Leanny have you tried downloading the C++ files? 
![image](https://user-images.githubusercontent.com/11446437/146233807-1b97f429-659a-4950-a48b-a024c8591fd8.png)

**Comment by Drakhi07** [comment] 2021-12-15 17:27
I have the same issue but it only happens when scanning weapons or characters. Works fine for artifacts

**Comment by Leanny** [comment] 2021-12-15 18:12
@Andrewthe13th yes, that is not the issue though. After some debugging it looks like Itto and Gorous missing key. I guess this will be fixed with the auto updater from the datamined DB

**Comment by LightningDantes** [comment] 2021-12-15 21:27
So everything is updated and nothing happens in error log section it just instantly crashes after my nickname appears at navigation section.

**Comment by LightningDantes** [comment] 2021-12-15 22:16
thats what i got so far from runnung original project in Visual studio
![Screenshot2](https://user-images.githubusercontent.com/32832320/146273430-68201228-381b-4dd9-b163-5c1f2c0ce4db.jpg)

**Comment by Cupcak3** [comment] 2021-12-16 07:28
@LightningDantes Can you run the debugger and go line by line until it crashes? It's not apparent what's the cause from your screenshot.

@Leanny Yes index range crashes are likely because new things haven't been hardcoded in yet. If you really want to scan the new characters, you can hardcode them yourself into their the lists or you can clone this repo's master branch has the code for the updater. It hasn't been put out as a release yet but I think it should be stable enough.

**Comment by MrPolloo** [comment] 2021-12-16 15:51
i have this problem also when using GOOD format, but when using seelie format it works normally

**Comment by LightningDantes** [comment] 2021-12-16 19:34
Seems like this causing problem
![Screenshot5](https://user-images.githubusercontent.com/32832320/146436118-f28ac3de-e1a8-4331-afb6-f22bbf20ec3e.jpg)
cuz i added 2 stop points for degug after lane 207 it still running but after 59 i am getting  there is an exception on picture above
also i got something else from debuging
![Screenshot3](https://user-images.githubusercontent.com/32832320/146436394-da9573cc-8a9d-4378-a993-e84ac6e3ac2c.jpg)
![Screenshot4](https://user-images.githubusercontent.com/32832320/146436453-66ddf4fe-6f57-42f6-b152-7c5a1084ace5.jpg)
but this two came up after  i did suggested changes from visual studio (changing/fixing format for line 207 and it recomends to set parameter for scraper)

**Comment by Cupcak3** [comment] 2021-12-16 20:33
Hmm I don’t believe there should be any parameters for Scraper.cs and the exceptions it’s throwing don’t tell us much either. If you can single out the line in RestartEngines that crash it would tell us more. 

As for the last two screenshots, that’s expected behavior if it can’t find any items in your inventory to click. There’s nothing written in to the program to check that it navigates correctly so it may have tried to scan your inventory when the weapons page isn’t open. 

Unfortunately my internet has been down today so I can’t exactly do a deep dive on what’s going on. However, I am confident that whatever bugs you’re encountering are fixed on the main branch if you would like to take a look at that.

**Comment by LightningDantes** [comment] 2021-12-16 20:36
@Cupcak3 so basicly after starting scan it shows my nickname in navigation tab but in game it never exits paimon menu and it crashes trying to scan

**Comment by Cupcak3** [comment] 2021-12-16 20:45
Okay. It sounds like one of two things to me:

1. You rebound your escape key so it doesn’t exit the menu
2. You set a breakpoint before the game tries to exit the menu which brings focus away from Genshin. Genshin needs focus for the menu navigation to work. This would make debugging tricky as you’d need to know when Kamera does it’s navigation.

**Comment by LightningDantes** [comment] 2021-12-16 20:47
so it runs restart engines fine then it shows nickname and puts mouse into game and immidiatly stops
none of my keys is rebinded

**Comment by LightningDantes** [comment] 2021-12-16 20:55
okey for some reason it decided to work this time but all artifacts give "Unable to validate information for artifact"

**Comment by Cupcak3** [comment] 2021-12-16 21:56
If you are using the main branch build there’s an additional step before you can scan. It’s automated so under options all you need to do is update every list. Sorry there’s no documentation on that yet. 

I will work to make validation errors more specific and helpful.

**Comment by Andrewthe13th** [comment] 2021-12-17 00:56
new release has been made public

**Closed** 2022-01-11 22:28 UTC
