### ISSUE TITLE
Could not determine character's name or element

### ISSUE THREAD

**Issue by Vasilic-Maxim** [Andrewthe13th/Inventory_Kamera#119] opened 2021-12-18 11:37 UTC
Hi there. I tried to use the latest version of the program. Unfortunately, I got an error when the program was trying to get Sangonomiya Kokomi's data. Here are the steps to achieve the same result.

1. change Genshin Impact window resolution to 1280 x 720
2. enter Paimon's menu
2. open the IK (Inventory Kamera)
3. select all items from the "Scan Items" list
4. press the button "Scan Genshin"

I repeated the process twice and got the same results.

1. IK successfully scans weapons, artifacts, and all the characters before Sangonomiya Kokomi
2. when IK reaches Sangonomiya Kokomi it stops for 10-15 seconds
3. after that IK continues scanning the "Character Development Items" and the "Material" sections

I also have trouble with character talent books, crowns, and maybe some other items. At least they are not displayed correctly in [Genshin Center Planner](https://genshin-center.com/planner). I will check the generated JSON and will make an update on this topic.

**Comment by Vasilic-Maxim** [comment] 2021-12-18 13:07
The problem that was related to importing data to the [Genshin Center Planner](https://genshin-center.com/planner) is not related to the application. Some names of materials they and at least one other scanner are using are not following completely "GOOD" format. Because of that half of the materials generated by IK are just skipped by the [Genshin Center Planner](https://genshin-center.com/planner) importer.

**Comment by Cupcak3** [comment] 2021-12-18 20:11
This does not look to be an issue with Kamera.

I have cross referenced the GOOD materials example from Amenoma [here](https://github.com/daydreaming666/Amenoma/blob/main/AmenomaDevDocs/examples/materials.GOOD.json) and I do not believe they have the right format for their materials, therefore I do not believe Genshin Center Planner does not either. Since Genshin Center Planner is not open source I cannot tell which is at fault for the incorrect material keys. I suspect the issue is with prepositions and indefinite articles (a, an, of, the, etc.) not being capitalized when they should be. I have also looked in to more of how Amenoma uses GOOD for weapons and artifacts and they _**do**_ use correct naming conventions for in their examples doc so this is definitely on. We are using GO's definition of GOOD [found here](https://frzyc.github.io/genshin-optimizer/#/doc/KeyNaming) which lays out the naming convention well.

As for materials that *are* in GOOD format and do not have any of the above issue please list them here.

**Comment by Cupcak3** [comment] 2021-12-18 20:45
Sorry I just realized I only answered the second half of your post. Characters with long names cause the scanner to hang currently. There is a possible fix on the dev branch for this already. You can skip to the next character whenever the scanner hangs trying to scan a character with a long name as a workaround for now.

**Comment by Vasilic-Maxim** [comment] 2021-12-19 02:17
The problem with Genshin Center Planner importer appears because their format differs a little from the original "GOOD". I looked at JSON generated by Amenoma, which is currently acceptable by Genshin Center Planner, and it turns out that some names are different from "GOOD".

Thanks for your reply!

**Comment by Cupcak3** [comment] 2022-01-11 22:37
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.

**Comment by Vasilic-Maxim** [comment] 2022-01-12 07:57
Hi. With the new release, I have no problems with the characters' scanner. Good work! However, the weapon that Kokomi uses was not defined correctly. Moreover, the 'Thrilling Tales of Dragon Slayers' is not even present in the weapon list. Do you have such a problem?

**Comment by Vasilic-Maxim** [comment] 2022-01-12 07:59
Hi. With the new release, I have no problems with the characters' scanner. Good work!

**Closed** 2022-01-12 08:09 UTC
