### ISSUE TITLE
weapon scanner 

### ISSUE THREAD

**Issue by nickkcin02** [Andrewthe13th/Inventory_Kamera#51] opened 2021-11-08 15:03 UTC
My weapon has 111, but the program read 11 and started scanning on the second row and then finished with 11 weapons.
manually fixed by consuming some 1 stars until 109 left and scan again, it works perfectly.

**Comment by Cupcak3** [comment] 2022-01-11 21:55
Duplicate of #48

**Closed** 2022-02-06 19:53 UTC
Labels: duplicate
