### ISSUE TITLE
Scan gets aborted immediately

### ISSUE THREAD

**Issue by iBroodx** [Andrewthe13th/Inventory_Kamera#216] opened 2022-02-11 13:11 UTC
im getting this response after trying to start a scan:

The type initializer for 'InventoryKamera.Scraper' threw an exception.

   at InventoryKamera.Scraper.RestartEngines()

   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 66

   at InventoryKamera.Form1.<StartButton_Clicked>b__12_0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 180

**Comment by ellimiku** [comment] 2022-02-19 20:55
Same issue here... May I ask which version of windows you're using? I recently switched to windows 11 and I don't know if that could have an influence (some of the other "scanners" also don't work anymore for me)

**Comment by iBroodx** [comment] 2022-02-20 14:59
yea im on windows 11 but i 've had 11 for weeks now and it worked in the beginning when i was still on 11

**Comment by Cupcak3** [comment] 2022-02-20 19:54
Please check out the note in the latest release patch notes. One user found that installing both the [x64 and x86 C++ 2015-2022 (or 2019) redistributable packages from Microsoft](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) fixed this error. I develop on Windows 11 and have the 2015-2019 versions installed for each as you can see below.

![image](https://user-images.githubusercontent.com/8845977/154861603-e6387622-c351-414e-bee3-24c3a6bcfdc6.png)

**Comment by iBroodx** [comment] 2022-02-25 20:18
downloaded both still not working.

**Comment by Cupcak3** [comment] 2022-07-23 18:36
Duplicate of #126

**Closed by Cupcak3** 2022-07-23 18:36 UTC
