### ISSUE TITLE
Some "Character Develomemnt Items" lines are missing and some numbers are wrong.

### ISSUE THREAD

**Issue by djax666** [Andrewthe13th/Inventory_Kamera#174] opened 2022-01-15 01:39 UTC
Hello, 
I get count errors or missing in "Character Develomemnt Items"
For exemple, my "SergeantsInsignia" count is 11 and Inventory_Kamera tells its 1.

Some lines are missing, like one line containing in my inventory "whopperflowernectar, shimmeringnectar, sturdyboneshard, fragileboneshard, kageuchihandguard,oldhandguard,chaosaxis".

View in my Genshin Impact:
![Capture](https://user-images.githubusercontent.com/35227325/149603120-ffabff9c-f067-4c83-b035-30bab3d81f19.PNG)

View of the generated GOOD file in genshin-center.com
![Screenshot 2022-01-15 at 02-10-10 Plannificateur d'Ascension - Genshin Center](https://user-images.githubusercontent.com/35227325/149603127-6c24a478-8d40-459f-933f-c6ba22319838.png)

My PhilosophiesOfFreedom count is 2, but Inventory_Kamera tells its 11.
The rest (7 lines) after  PhilosophiesOfFreedom  is not taken in account

View in my Genshin Impact:
![Capture_2](https://user-images.githubusercontent.com/35227325/149603550-e02937d9-fbb7-4ca4-9551-89d235ef39af.PNG)
![Capture_3](https://user-images.githubusercontent.com/35227325/149603762-e758f68f-1f23-43f7-9eeb-6448a767831d.PNG)

View of the generated GOOD file in genshin-center.com :
![Screenshot 2022-01-15 at 02-21-08 Plannificateur d'Ascension - Genshin Center](https://user-images.githubusercontent.com/35227325/149603557-fafdecec-1132-4d7e-a69e-ea218e7b5dfd.png)

I'm using Inventory_KameraV1.1.1-prerelease.

**Comment by Cupcak3** [comment] 2022-01-15 09:42
I'll answer this in parts:

Your issue with the incorrectly parsed numbers is a known issue. I've found that some digits (namely 1 and 4) sometimes trip up the scanner due to their size and font. There is some we can do to improve accuracy but it will take some time without some sort of standardized way of submitting inaccuracies.

Rows/columns of items being skipped might be a result of the blurred background interfering with locating items on the screen. Usually moving around in the world can be enough to fix this.

At the point in which the scanner stopped short of scanning the rest of your inventory, did it start scanning from bottom to top, right to left? All the materials sections of the scanner rely on reading the item on the right side of the screen. Sometimes it clicks too fast and the next item hasn't been clicked by the time the scanner checks to see what item is there. Please increase the delay a bit and let me know if the issue with stopping short continues.

**Comment by djax666** [comment] 2022-01-16 17:21
I set the display mode of GI as "1600x900 Windowed". The scanner delay was already set on 100ms.

I noticed that the kamera doesn't go down enough.

When it goes from the bottom to the top, the frame where the number is, is shadowed with the background and half of the number is visible.

**Comment by Cupcak3** [comment] 2022-01-20 03:40
We check for when we are attempting to scan something that's already been scanned to determine if we're near the bottom of the inventory page. At which point we do a number of scrolls to ensure the lines of items have their quantities visible. Obviously if Kamera stops short of the bottom then there's a good chance that those last few rows can't get their quantities scanned since they're not completely visible.

Does this incorrect behavior happen on other resolutions for you?

Thanks for the feedback. We will continue to look for more optimized ways for material scanning.

**Comment by djax666** [comment] 2022-02-11 13:53
Yes, I tried different resolutions with no much luck.

**Comment by BobbyWibowo** [comment] 2022-03-03 16:41
Can confirm that neither 1280x720 nor 1600x900 worked well with materials scanning on my end
Errors rate is also a bit too high to be relied upon honestly 😞 

I'll try to also submit sample generated results vs actual values screenshots or something in here maybe, if that helps

> I've found that some digits (namely 1 and 4) sometimes trip up the scanner due to their size and font.

Can also confirm those numbers seemingly cause errors a lot more often than others

**Comment by Cupcak3** [comment] 2022-07-23 17:42
I am marking this a Duplicate of #96 to consolidate issues

**Closed** 2022-07-23 17:43 UTC
Labels: duplicate
