### ISSUE TITLE
[BUG] Scanner freezes at the last page of artifact inventory (2.7)

### ISSUE THREAD

**Issue by Faahm** [Andrewthe13th/Inventory_Kamera#314] opened 2022-06-19 10:14 UTC
> **NOTE**
> Please describe on each question as much as you can. This will speeds up our bug fixing process.

[debug.log link here](https://pastebin.com/CRd4StGg)
## What happed? What is seems to be a bug?
 Scanner freezes at the last page of artifact inventory, it does not move on to characters, and does not scan every artifact 5* in the last page.
 N/A

## How to reproduce this issue
 Choose artifacts among the options then run the scanner and set the rarity to 5*
 N/A

## What seems to cause this issue?
 Possibly because it hasn't been updated for Genshin Impact 2.7
 N/A

## Expected behavior
 Scan every artifact 5* in the artifact inventory

## Info about your device
- Device Operating System : Windows 10
- Genshin Impact Version : 2.7
- Inventory Kamera Version : 1.2.6
- Screen resolution(s) affected : 1600x900

## Additional Notes / Remarks
 I checked my logs but there are no reports on freezing/errors

## Checklist before sending issue

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [x] I have checked Issue page and there is **none** that is related to mine.
- [x] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [x] I have filled in "Info about your device" section.
- [x] I have correctly set my character and inventory keys in Inventory Kamera
- [x] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

Additional checklist for Scanning issues
- [x] I tried setting the delay to maximum and still experiencing issues.
- [x] I have attached media and log files that Inventory Kamera generates.

**Comment by b4lesh** [comment] 2022-06-23 21:53
I have the same problem too. It may be because the last scroll is too small and the scanner can't handle it.

**Comment by Faahm** [comment] 2022-06-25 15:44
> 

For me, it was a bit less than half the inventory screen.

**Comment by TheFarix** [comment] 2022-07-05 11:53
While scanning artifacts, a random line will be skipped. This becomes especially problematic if your Minimum Artifact Rarity is equal to or less than your lowest artifact causing the scan to stall once it reaches the end of the list.

**Comment by Cupcak3** [comment] 2022-07-09 21:36
Hi there. Sorry for the late reply to this. I think I've found what might be causing this and hope to release it in a build soon.

**Comment by Cupcak3** [comment] 2022-07-23 20:10
V1.2.7 hopefully addresses this. Let us know if the issue persists

**Comment by Cupcak3** [comment] 2022-07-23 20:14
I'm also going to mark this as duplicate of #321 as it has some more discussion.

**Closed by Cupcak3** 2022-07-23 20:14 UTC
Labels: bug
