### ISSUE TITLE
Failed to parse quantity

### ISSUE THREAD

**Issue by lakandula12** [Andrewthe13th/Inventory_Kamera#338] opened 2022-07-25 17:30 UTC
### Current Behavior

![image](https://user-images.githubusercontent.com/109982770/180837818-57e58524-b304-4465-b9b8-856212bb320b.png)

### Expected Behavior

Other (please specify in additional notes)

### Reproduce a Behavior

1. Failed to count correct amount of items in the inventory

### Device OS

Windows 11

### Genshin Impact Version

2.8 (pre-release)

### Inventory Kamera Version

Other (please specify in additional notes)

### Screen resolution, screen mode, and UI scale

1280x720

### Additional notes and remarks

Nothing

### Evidence

![image](https://user-images.githubusercontent.com/109982770/180838404-5ace21f2-78f9-4f8d-a859-7898830359f0.png)

### Preflight Checklist

- [X] I have checked the issue page, and there were none that similar to the one I'm reporting.
- [ ] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I did not enable any image filtering software or plugins (ie. HDR, Image Sharpening, etc.) while scanning.
- [X] I use default keybindings or have configured keybindings to the scanner.

**Comment by Cupcak3** [comment] 2022-07-26 01:09
Hi there this is a duplicate of one of the pinned issues.

**Closed by Cupcak3** 2022-07-26 01:09 UTC
Labels: bug
