### ISSUE TITLE
Need help for first use

### ISSUE THREAD

**Issue by yvanmercer** [Andrewthe13th/Inventory_Kamera#246] opened 2022-03-18 15:49 UTC
I got this error

System.TypeInitializationException: Une exception a été levée par l'initialiseur de type pour 'InventoryKamera.Scraper'. ---> Tesseract.TesseractException: Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.

   à Tesseract.TesseractEngine.Initialise(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialValues, Boolean setOnlyNonDebugVariables)

   à Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialOptions, Boolean setOnlyNonDebugVariables)

   à Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode)

   à InventoryKamera.Scraper..cctor()

   --- Fin de la trace de la pile d'exception interne ---

   à InventoryKamera.Scraper.RestartEngines()

   à InventoryKamera.InventoryKamera.GatherData()

   à InventoryKamera.MainForm.<StartButton_Clicked>b__12_0()

**Comment by Cupcak3** [comment] 2022-05-16 03:29
Hi there, I know it's been a while since this issue was opened but [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5) has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!

**Comment by Cupcak3** [comment] 2022-07-23 18:50
Duplicate of #126

**Closed by Cupcak3** 2022-07-23 18:50 UTC
