### ISSUE TITLE
Minor Errors needs fixes

### ISSUE THREAD

**Issue by RohitM-IN** [Andrewthe13th/Inventory_Kamera#251] opened 2022-03-30 15:50 UTC
all other item scan was perfect just these 2 errors 
char dev materials log:
```
Failed to parse quantity for NorthlanderCatalystBillet
Failed to parse quantity for GoldenKoi
Failed to parse quantity for DivdaRay
```
Artificats log: (a bit big scanned 2-3 times and this one has least errors)
[Artificats Err log.txt](https://github.com/Andrewthe13th/Inventory_Kamera/files/8382011/Artificats.Err.log.txt)

**Comment by RootAndroid58** [comment] 2022-03-30 15:52
I happen to have the log for materials since it was done at last
![DivdaRay_Quantity](https://user-images.githubusercontent.com/28777412/160877712-a49a19ad-1c30-4306-bd49-8e949d39e2be.png)
![GoldenKoi_Quantity](https://user-images.githubusercontent.com/28777412/160877721-d24ab70c-1685-474b-bd46-cc4a44b10d61.png)
![NorthlanderCatalystBillet_Quantity](https://user-images.githubusercontent.com/28777412/160877724-0ee6be58-bdc2-474c-86ea-c6a2e07d731d.png)

**Comment by Scoterster86** [comment] 2022-04-12 20:24
Also getting the similar errors at 1920 x 1080 resolution and render resolution 1.1:
```
Failed to parse quantity for WeatheredArrowhead
Failed to parse quantity for MistGrass
Failed to parse quantity for PolarizingPrism
Failed to parse quantity for DarkStatuette
Failed to parse quantity for DewOfRepudiation
Failed to parse quantity for JuvenileJade
Failed to parse quantity for EverflameSeed
Failed to parse quantity for BloodjadeBranch
Failed to parse quantity for ShadowOfTheWarrior
Failed to parse quantity for ShardOfAFoulLegacy
Failed to parse quantity for SpiritLocketOfBoreas
Failed to parse quantity for TailOfBoreas
Failed to parse quantity for DvalinsPlume
Failed to parse quantity for NorthlanderCatalystBillet
Failed to parse quantity for Dawncatcher
Failed to parse quantity for Crystalfish
Failed to parse quantity for LungedStickleback
Failed to parse quantity for VenomspineFish
Failed to parse quantity for BrownShirakodai
Failed to parse quantity for PurpleShirakodai
Failed to parse quantity for RaimeiAngelfish
Failed to parse quantity for FormaloRay
```
Materials Logging Folder:
[materials.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/8476224/materials.zip)

**Comment by Cupcak3** [comment] 2022-05-16 03:17
Hi there, I know it's been a while since this issue was opened but [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5) has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!

**Comment by Cupcak3** [comment] 2022-07-23 18:53
Duplicate of #96

**Closed by Cupcak3** 2022-07-23 18:53 UTC
