### ISSUE TITLE
[BUG] Scanner skipping rows occasionally

### ISSUE THREAD

**Issue by rikai** [Andrewthe13th/Inventory_Kamera#321] opened 2022-07-10 23:12 UTC
## What happed? What is seems to be a bug?
A line of artifacts is skipped for scanning consistently when processing artifacts regardless of speed settings.
Example: https://user-images.githubusercontent.com/515221/178165351-0fdb6d4a-6b79-45db-ab10-2fe67a5d2c74.mp4

## How to reproduce this issue
Not sure of the cause so not sure how to reproduce, only know it's consistent in my setup.

## What seems to cause this issue?
Based on the artifact log images, it looks to be misaligning on this page for some reason:
![ArtifactInventory](https://user-images.githubusercontent.com/515221/178165653-33f1407a-a0b1-41fb-95bc-9a0968bf135e.png)
![ArtifactInventory10_8x4](https://user-images.githubusercontent.com/515221/178165531-a60bd507-1654-48fb-b0e6-810f84b0bd18.png)
[InventoryKamera.log](https://github.com/Andrewthe13th/Inventory_Kamera/files/9080039/InventoryKamera.log)

Please note that the green dotted border and overlay in the bottom left are from the image capture above but this also happens without the capture running in the same way.

## Expected behavior
I expect the line of 4-star artifacts to be scanned and not skipped over.

## Info about your device
- Device Operating System : Windows 10 Pro
- Genshin Impact Version : 2.8
- Inventory Kamera Version : 1.2.7
- Screen resolution(s) affected : 1920x1080

## Additional Notes / Remarks
Issue #312 seems to be similar but unclear if it is the same since no further information was provided.

## Checklist before sending issue

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [x] I have checked Issue page and there is **none** that is related to mine.
- [x] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [x] I have filled in "Info about your device" section.
- [x] I have correctly set my character and inventory keys in Inventory Kamera
- [x] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

Additional checklist for Scanning issues
- [x] I tried setting the delay to maximum and still experiencing issues.
- [x] I have attached media and log files that Inventory Kamera generates.

**Comment by rikai** [comment] 2022-07-14 08:00
I was not able to replicate it at other resolutions. In addition to that, it no longer appears to be happening now that I have gained a few more artifacts and the cups don't start the row any longer, so it could be tied to the recognition of the cups perhaps?

A working example of the same row with artifacts shifted from getting more earlier in the list:
![image](https://user-images.githubusercontent.com/515221/178932202-f675042e-17e6-4604-952b-1e224f4a6cd0.png)

**Comment by Grudge10** [comment] 2022-07-15 05:27
Same thing seems to happen to me as well. The scanner skips the second column to the left.

**Comment by Grudge10** [comment] 2022-07-15 09:50
After gaining new artifacts, it seems to be working fine, but it now doesn't scan the last row of artifacts.

**Comment by rikai** [comment] 2022-07-17 05:07
I finally got this to happen again so I can adequately test 1920x1080 vs another resolution. Decided it made the most sense to test against other 16:9 resolutions.

1920x1080:
![ArtifactInventory7_8x4](https://user-images.githubusercontent.com/515221/179384393-14763ce0-0a75-4738-93b6-c8c8ec42e90d.png)
Additionally tested this a second time after removing the 'new' tags on the artifacts on that line, but the line is still skipped.

1600x900:
Did not happen.

1280x720:
Did not happen.

**Comment by nickkcin02** [comment] 2022-07-26 18:41
I have this problem too, only at 1920x1080 resolution, I tried in 1600x900 and it works perfectly without any skipping.
The bug happened at the start of the 26th row (the 201st piece).

**Comment by Cupcak3** [comment] 2022-08-02 19:14
It sounds like this the item detection algorithm is losing accuracy under some conditions. I'll see what I can do about improving that. It's going to stay low priority since the workaround seems to be just be changing the number of artifacts in your inventory.

**Comment by Julienraptor01** [comment] 2022-09-09 22:28
From my experience this bug consitently happen on artifacts 1 page before the last page like if it was anticipating the difference of position which does exist in last page no matter the res is use, i can give a record with OBS if needed

**Comment by Julienraptor01** [comment] 2022-09-09 23:07
i think i have a critical info :
if you set your res to 1600x900 so in windowed mode for a 1920x1080 display and then put it in fullscreen with alt+enter key combo the bug seems fixed
i play with every settings at the highest possible (except resolution here)

**Comment by TechnoStone** [comment] 2022-10-20 18:44
1920x1080 window and it skips row after second scroll. Also happens on 1920x1200 and with maximum scanner delay


https://user-images.githubusercontent.com/26044948/197031656-590da262-d37f-4154-89c7-8dc493e7fd64.mp4

**Comment by Nikolas-VIII** [comment] 2022-11-05 15:15
To add to this: My experience on 1.3.1:
On 1440p it skips rows and there is a visible shift after every page scroll (the top row creeps a bit higher every time).
On 1080p it still skips rows but with no apparent shift.
On 900p it works correctly as far as I can see. However, two single 3 star artifacts were missed for some reason.

**Comment by diogovk** [comment] 2022-12-05 19:08
I had the same problem, which I believe I can reproduce consistently.
When using the software in windowed 1080p, it works fine up until a point, but then skips a row.
When I switched the resolution to 1680x1050 all artifacts were scanned successfully.

It looks like the first row being skipped is always row number 56. After scrolling, the first line being shown, which is line 56, hasn't been scanned yet, but Kamera jumps to the second line being shown, row number 57.

**Comment by Matthew-X** [comment] 2022-12-19 13:35
Still happening it skips my Pre last line.

**Comment by diogovk** [comment] 2022-12-19 16:55
The same problem is happening with version 1.3.4

**Comment by Julienraptor01** [comment] 2022-12-19 17:42
> i think i have a critical info :
> if you set your res to 1600x900 so in windowed mode for a 1920x1080 display and then put it in fullscreen with alt+enter key combo the bug seems fixed
> i play with every settings at the highest possible (except resolution here)
> i tried to record with OBS but genshin take so much perf i couldn't

You can use this as a temporary solution

**Comment by kazerniel** [comment] 2023-02-07 23:02
Encountered this bug for the first time too. It skipped row 26 on a 1920x1080 resolution. Tried twice, happened both times, with the same row. (Can't remember having this bug before, but maybe just didn't notice.)
![image](https://user-images.githubusercontent.com/5689996/217385894-74c1be28-45b2-4bc3-a6bf-47e2e2a93b7c.png)
Switching to windowed 1600x900 fixed it for the time being.

**Comment by Cupcak3** [comment] 2024-02-03 22:33
I am closing this in favor of #312

**Closed by Cupcak3** 2024-02-03 22:33 UTC
Labels: bug
