### ISSUE TITLE
Cannot recognize 511

### ISSUE THREAD

**Issue by rtagulin** [Andrewthe13th/Inventory_Kamera#91] opened 2021-12-08 12:18 UTC
Kept recognizing 511 artifacts as 51 artifacts, so it would only scan 51 of my artifacts. Scan proceeded when I acquired 3 more artifacts. TYSM!

**Comment by Cupcak3** [comment] 2021-12-10 02:59
The scanner has trouble with repeat digits next to each other. As you found, managing the number of artifacts in your inventory is a good workaround. We're working on this issue but it's not a priority at the moment.

**Comment by Cupcak3** [comment] 2022-01-11 22:24
Duplicate of #48

**Closed** 2022-07-23 17:39 UTC
Labels: duplicate
