### ISSUE TITLE
[BUG]  All Normal Attack Talent levels are scanned as 1 lower

### ISSUE THREAD

**Issue by Nikolas-VIII** [Andrewthe13th/Inventory_Kamera#323] opened 2022-07-14 13:09 UTC
## What happed? What is seems to be a bug?

All Normal Attack Talent levels are scanned as 1 lower. Talent level 1 is listed as 0 in the json file etc.

## What seems to cause this issue?

The fix in the latest version 1.2.7 for Tartaglia's passive seems apply to all characters, instead of just him/his party. (Only tested when Tartaglia was not in the Party).
Only Tartaglia's Level was read correctly.

## Info about your device
- Device Operating System : Win 11
- Genshin Impact Version : 2.8
- Inventory Kamera Version : 1.2.7
- Screen resolution(s) affected : 2560x1440

> Instruction: Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:

- [x] I have checked Issue page and there is **none** that is related to mine.
- [x] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [x] I have filled in "Info about your device" section.
- [x] I have correctly set my character and inventory keys in Inventory Kamera
- [x] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

**Comment by lokyst** [comment] 2022-07-22 21:27
This is happening to me too.

**Comment by Cupcak3** [comment] 2022-07-23 18:26
Duplicate of #279 There is a PR for this but I do not know the exact behavior of the passive. Without owning the character myself I want to be sure I know how it works before attempting to fix

**Closed by Cupcak3** 2022-07-23 18:26 UTC
Labels: bug
