### ISSUE TITLE
Quanity Screenshot misalignment, leads to incorrect parsing

### ISSUE THREAD

**Issue by savitsme** [Andrewthe13th/Inventory_Kamera#464] opened 2023-08-15 20:58 UTC
### Current Behavior

it looks like the quantity screenshot is sometimes misaligned, causing
-- wrong quantities
-- "Failed to parse quantity for "

This misalignment doesnt seem to happen when scanning
- first page
- last page
- last row in reverse

but it does consistently happen in the rest of the cases

This is both in Character Development Items and Materials

<img width="125" alt="ShimmeringNectar_Quantity" src="https://github.com/Andrewthe13th/Inventory_Kamera/assets/47488157/f6ef1cff-c092-44a2-8905-e20a1ccd7bcf">

### Expected Behavior

The scanner to correctly exports the data

### Reproducing a Behavior

3840x2160 Fullscreen Resolution
Scan with either Character Development Items and or Materials enabled

### Device OS

Windows 10

### Genshin Impact Version

3.8

### Inventory Kamera Version

1.3.9

### Screen resolution, screen mode, and UI scale

3840x2160 Fullscreen

### Evidence

[logging4kFS.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/12352613/logging4kFS.zip)
- .good export
- logging folder

https://github.com/Andrewthe13th/Inventory_Kamera/assets/47488157/86512729-bea7-465b-ae1b-3a6022e315e2
- screen recording, showing part of the first and second page

items that were falsely quantised or failed to parse in the first two rows of 'page 2' (see video)
```
NameOfItem,CorrectQuanity,ParsedQuanity,ParsingFailed
RecruitsInsignia,603,60,
GoldenRavenInsignia,22,9,
TreasureHoarderInsigina,488,1,
ShimmeringNectar,98,0,X
WhopperflowerNectar,483,842,
SturdyBoneShard,68,0,X
FragileBoneShard,357,57,
FamedHandguard,2,0,X
OldHandguard,321,291,
ChaosOculus,12,10,
ChaosGear,862,0,X
```

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by savitsme** [comment] 2023-08-18 17:53
Tested again in 4.0 and its mostly the same as described before, except that the first page now is also affected, and the overall error rate (both incorrect and failed) feels a lot higher to the point where it failing is the norm

**Comment by Selixuz** [comment] 2023-11-27 22:50
i'm having the same issue with my game at 1920x1080 fullscreen, and it seems like its always the same items.
for example: hero's wit, chaos oculus, crown of insight. always have the wrong value, before my last crown i had 17 and it was counting 117, and now i have 18 and its only counting 1 every scan.

**Comment by Cupcak3** [comment] 2024-02-03 21:57
This is a duplicate of the pinned issue. I don't have much interest in improving material scanning much at the moment

**Closed by Cupcak3** 2024-02-03 21:57 UTC
Labels: bug
