### ISSUE TITLE
HDR display breaks scanner

### ISSUE THREAD

**Issue by derekxwu** [Andrewthe13th/Inventory_Kamera#385] opened 2022-09-18 19:33 UTC
### Current Behavior

HDR washes out SDR screenshots, breaking Inventory Kamera's OCR. Windows 11 pushes HDR/Auto HDR heavily, so it's becoming easier to encounter this.

It seems this already a known issue, but doesn't fail cleanly. Instead, the scanner behaves erratically - 2* weapons scan as Rust with negative refines, rows of artifacts are skipped, etc.
HDR being a source of issues is also not mentioned in the software or README - just the checklist for bug reports.

Proposed fix: Scanner should detect HDR and promptly fail with a user-friendly message. There may be a Windows 11 API to check if auto HDR is enabled, or the Paimon menu could be used as a litmus test.
![1663528690](https://user-images.githubusercontent.com/2723238/190924698-aa2b0eed-b3dc-4aa6-8508-91f9925e3b3e.png)

### Expected Behavior

The scanner stops scanning

### Reproducing a Behavior

Run Genshin in HDR via Windows 11 Auto HDR.

### Device OS

Windows 11

### Genshin Impact Version

3.0

### Inventory Kamera Version

1.3

### Screen resolution, screen mode, and UI scale

1080p, 720p, 900p

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [ ] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment] 2024-02-03 22:36
Duplicate of #164

**Closed by Cupcak3** 2024-02-03 22:36 UTC
Labels: bug
