### ISSUE TITLE
Weapon Scanner Not Reading correctly

### ISSUE THREAD

**Issue by ctm1992** [Andrewthe13th/Inventory_Kamera#84] opened 2021-12-04 17:13 UTC
![image](https://user-images.githubusercontent.com/95541648/144718268-64419212-3b10-4cfb-9d5b-bb5842ebf6d9.png)
![image](https://user-images.githubusercontent.com/95541648/144718316-056f476f-6610-4d76-ba29-39aa313f2760.png)

As you can see in the pictures above, I have 226 weapons, but the scanner is only reading 26 of them. It also appears that the scanner doesn't start at the top of the inventory and misses the first row of weapons in the inventory.

**Comment by ctm1992** [comment] 2021-12-04 17:25
It would appear that this is related to issues with 2 of the same number consecutively in a total. I reduced to 215 weapons and the scanner appears to operate correctly

![image](https://user-images.githubusercontent.com/95541648/144718696-293d674b-1e97-4d8a-8524-d49abc0bf3de.png)

**Comment by Andrewthe13th** [comment] 2021-12-04 17:30
Interesting. I will be testing this

**Comment by Hyweed** [comment] 2021-12-04 22:26
![imagem](https://user-images.githubusercontent.com/57677905/144726162-fe62f417-2e90-44f8-a4d0-523e7fdc94c2.png)

This is what's happening to me:

It's reading fine until the line that starts with the skyrider greatsword, but after that, the auto adjusting of the page looks like it snaps to the bottom of the page and misses the line right after it, the one that starts with the cool steel, and it's always that the problem, extremely consistent. The shift of the page is too sudden and it caused this. Not sure if it's useful but the cool steel line it's the 5th counting from the bottom, (I'd like to add that the snapping is really violent and it seems that even misses the first scan right after the snap, in my case I missed 8 weapons, and each line only has 7: last image although i don't really know what genshin counts in the 104 in the top of the inventory)

![imagem](https://user-images.githubusercontent.com/57677905/144726232-111d2f1e-ef93-48bb-b3c9-677198ac2259.png)

He should be seeing the first image, but what he sees while scanning after the snap is the second one, so it caused it to miss the scan of the 5th line counting from the end, going from the 6th, to the 5th, then the 4th, then the 3rd, the 2nd and last line, ending after that, like this in the console:

![imagem](https://user-images.githubusercontent.com/57677905/144726317-537b1dc9-4fdf-4069-8247-32e46b9ef417.png)

**Comment by Andrewthe13th** [comment] 2021-12-04 23:57
Have u tried adding a delay to the scanner. Try setting the scanner delay to 50ms. That should fix ur issue. Let me know if it does or doesn't.

**Comment by Hyweed** [comment] 2021-12-05 10:01
That's was good point, but it does exactly the same for some reason 🤔

![imagem](https://user-images.githubusercontent.com/57677905/144742010-654227bf-01b2-4553-a5b4-3ed553bcbdfd.png)

The snap didn't change, he goes really well line to line, but when he can't go lower it kinda freaks out for some reason. Worth a try though.

**Comment by Andrewthe13th** [comment] 2021-12-05 13:55
Ya it's 8 weapons cause 2 star weapons are not counted so it's really 7 weapons which are all the weapons in the top row.. So its either the scroll was too fast or the way I count at the end. I will try to fix this issue

**Comment by Cupcak3** [comment] 2022-01-11 22:16
Duplicate of #48

**Closed** 2022-07-23 17:39 UTC
Labels: duplicate
