### ISSUE TITLE
some artifacts get mistaken into Gamblers set

### ISSUE THREAD

**Issue by Athenaxdd** [Andrewthe13th/Inventory_Kamera#249] opened 2022-03-26 14:12 UTC
As title said, some of the artifacts get scanned and when uploaded to Genshin Optimizer they turn into Gambler set

**Comment by lokyst** [comment] 2022-04-15 15:15
I had the same issue. Increasing my resolution to 1920 x 1200 windowed seems to have resolved it for now.

**Comment by kazerniel** [comment] 2022-04-18 00:24
Same issue. 1280 x 800 resolution. In recent weeks about 1/4 of my Gladiator pieces are scanned as Gambler.

(Sadly I can't make my resolution any higher while keeping it windowed.)

**Comment by Cupcak3** [comment] 2022-07-23 18:51
Duplicate of #240

**Closed by Cupcak3** 2022-07-23 18:51 UTC
