### ISSUE TITLE
Inaccurate OCR when parsing quantity

### ISSUE THREAD

**Issue by Mete0** [Andrewthe13th/Inventory_Kamera#253] opened 2022-04-04 17:08 UTC
It seems that no matter which resolution I use, there is around 10-20% of the items that fail to parse quantity. Anemona doesnt have this problem. Maybe the model needs to be updated?

**Comment by Cupcak3** [comment] 2022-05-16 03:17
Hi there, I know it's been a while since this issue was opened but [V1.2.5](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.5) has been released. Hopefully fixes in this version fix your problem. Please let us know if they're resolved, thanks!

**Comment by Tetranor89** [comment] 2022-07-10 18:53
Hi dude, the bug is still present in version 1.2.7. Probably due to the recent game patches?

Another bug is that you have to scan characters, artifacts and materials separately otherwise the character scan stops at the first.

however, being able to load multiple databases on the site this is not a problem.

Thank you for your work, i really appreciate it :)

**Comment by Cupcak3** [comment] 2022-07-23 18:55
Duplicate of #96

**Closed by Cupcak3** 2022-07-23 18:55 UTC
