### ISSUE TITLE
Failed to parse quantity for item (character develop item , Material)

### ISSUE THREAD

**Issue by AzzinothKG** [Andrewthe13th/Inventory_Kamera#340] opened 2022-07-28 07:40 UTC
### Current Behavior

I've found this issue when scan character develop item , Material
The program cant parse quantity item.

### Expected Behavior

Scanner continues to scan

### Reproduce a Behavior

i dont understand :)

### Device OS

Windows 10

### Genshin Impact Version

2.8

### Inventory Kamera Version

1.2.7

### Screen resolution, screen mode, and UI scale

1920x1080 windowed

### Evidence

![image](https://user-images.githubusercontent.com/98711283/181448986-7cc3499a-54a9-4377-b469-9f9e055992b7.png)

### Preflight Checklist

- [X] I have checked the issue page, and there were none that similar to the one I'm reporting.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I did not enable any image filtering software or plugins (ie. HDR, Image Sharpening, etc.) while scanning.
- [X] I use default keybindings or have configured keybindings to the scanner.

**Comment by Cupcak3** [comment] 2022-07-29 01:45
This is a duplicate of one of the pinned issues.

**Closed by Cupcak3** 2022-07-29 01:45 UTC
Labels: bug
